#development:
#  adapter: mysql2
#  database: splendor_dev
#  encoding: utf8
#  username: root
#  password: 5zlqkdzl
#  host: localhost
#  reconnect: true
#
development:
  adapter: postgresql
  host: localhost
  username: postgres
  database: splendor_dev
  port: 5432
  password:

production:
  adapter: postgresql
  host: ec2-54-83-5-151.compute-1.amazonaws.com
  username: cdjxodxejubgnp
  database: ddn0b1qe71gmtf
  port: 5432
  password: KqlWS-hmp0jWLrMq261o-5EIcQ
